name: build-android

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install npm packages
        run: npm install --legacy-peer-deps

      - name: Jetify
        run: npx jetify

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: mattermost-apk
          path: android/app/build/outputs/apk/debug/*.apk
